"""initial_tables

Revision ID: 625bb7317b3b
Revises: 
Create Date: 2026-02-24 19:52:24.248501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625bb7317b3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('admin_password', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_admin_users_active', 'admin_users', ['is_active'], unique=False)
    op.create_index('idx_admin_users_user_id', 'admin_users', ['user_id'], unique=False)
    op.create_table('ai_model_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_service', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('cost_per_1k_input', sa.Float(), nullable=False),
    sa.Column('cost_per_1k_output', sa.Float(), nullable=False),
    sa.Column('credits_per_1k_tokens', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_service', 'model_name')
    )
    op.create_index('idx_ai_model_service', 'ai_model_pricing', ['ai_service', 'is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_event', 'audit_logs', ['event'], unique=False)
    op.create_index('idx_audit_logs_sensitivity', 'audit_logs', ['sensitivity'], unique=False)
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('allow_file_upload', sa.Boolean(), nullable=False),
    sa.Column('allow_comment', sa.Boolean(), nullable=False),
    sa.Column('max_file_size', sa.Integer(), nullable=False),
    sa.Column('allowed_extensions', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('write_permission', sa.String(length=20), nullable=False),
    sa.Column('read_permission', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('name_translations', sa.Text(), nullable=True),
    sa.Column('description_translations', sa.Text(), nullable=True),
    sa.Column('key_translations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_key')
    )
    op.create_index('idx_boards_key', 'boards', ['board_key'], unique=False)
    op.create_index('idx_boards_public', 'boards', ['is_public'], unique=False)
    op.create_index('idx_boards_sort', 'boards', ['sort_order'], unique=False)
    op.create_table('currency_exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.Text(), nullable=False),
    sa.Column('currency_name', sa.Text(), nullable=False),
    sa.Column('currency_symbol', sa.Text(), nullable=False),
    sa.Column('rate_to_usd', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_code')
    )
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_id', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('level_num', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('request_path', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('error_id')
    )
    op.create_index('idx_error_logs_created', 'error_logs', ['created_at'], unique=False)
    op.create_index('idx_error_logs_expires', 'error_logs', ['expires_at'], unique=False)
    op.create_index('idx_error_logs_level', 'error_logs', ['level_num'], unique=False)
    op.create_index('idx_error_logs_source', 'error_logs', ['source'], unique=False)
    op.create_table('stripe_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_webhook_events_id', 'stripe_webhook_events', ['event_id'], unique=False)
    op.create_index('idx_webhook_events_type', 'stripe_webhook_events', ['event_type', 'processed'], unique=False)
    op.create_table('subscription_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=False),
    sa.Column('base_usage', sa.Integer(), nullable=False),
    sa.Column('bonus_rate', sa.Float(), nullable=False),
    sa.Column('bonus_usage', sa.Integer(), nullable=False),
    sa.Column('total_usage', sa.Integer(), nullable=False),
    sa.Column('expire_days', sa.Integer(), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('is_popular', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_type')
    )
    op.create_index('idx_subscription_packages_active', 'subscription_packages', ['is_active', 'sort_order'], unique=False)
    op.create_index('idx_subscription_packages_type', 'subscription_packages', ['package_type'], unique=False)
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('request_tokens', sa.Integer(), nullable=False),
    sa.Column('response_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('request_type', sa.Text(), nullable=True),
    sa.Column('mindmap_id', sa.Text(), nullable=True),
    sa.Column('node_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_usage_created', 'token_usage', ['created_at'], unique=False)
    op.create_index('idx_token_usage_service', 'token_usage', ['service', 'model'], unique=False)
    op.create_index('idx_token_usage_user_created', 'token_usage', ['user_id', 'created_at'], unique=False)
    op.create_table('user_drive_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('drive_enabled', sa.Integer(), nullable=False),
    sa.Column('drive_path', sa.Text(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('sync_mode', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_drive_settings_user', 'user_drive_settings', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('facebook_id', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('totp_secret', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_facebook_id', 'users', ['facebook_id'], unique=False)
    op.create_index('idx_users_google_id', 'users', ['google_id'], unique=False)
    op.create_index('idx_users_totp_enabled', 'users', ['totp_enabled'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_table('users_credits',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('user_type', sa.Text(), nullable=False),
    sa.Column('free_credits', sa.Integer(), nullable=False),
    sa.Column('service_credits', sa.Integer(), nullable=False),
    sa.Column('paid_credits', sa.Integer(), nullable=False),
    sa.Column('free_credits_expiry', sa.Date(), nullable=True),
    sa.Column('service_credits_expiry', sa.Date(), nullable=True),
    sa.Column('paid_credits_expiry', sa.Date(), nullable=True),
    sa.Column('subscription_status', sa.Text(), nullable=False),
    sa.Column('subscription_package', sa.Text(), nullable=True),
    sa.Column('subscription_start_date', sa.Date(), nullable=True),
    sa.Column('subscription_end_date', sa.Date(), nullable=True),
    sa.Column('auto_renewal', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.Text(), nullable=True),
    sa.Column('stripe_subscription_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_users_credits_status', 'users_credits', ['subscription_status'], unique=False)
    op.create_index('idx_users_credits_type', 'users_credits', ['user_type'], unique=False)
    op.create_index('idx_users_stripe_customer', 'users_credits', ['stripe_customer_id'], unique=False)
    op.create_table('access_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_id', sa.String(length=16), nullable=False),
    sa.Column('mindmap_id', sa.String(length=255), nullable=False),
    sa.Column('permission', sa.String(length=10), nullable=False),
    sa.Column('ip_whitelist', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    sa.UniqueConstraint('key_id')
    )
    op.create_index('idx_access_keys_is_active', 'access_keys', ['is_active'], unique=False)
    op.create_index('idx_access_keys_key_hash', 'access_keys', ['key_hash'], unique=False)
    op.create_index('idx_access_keys_key_id', 'access_keys', ['key_id'], unique=False)
    op.create_index('idx_access_keys_mindmap_id', 'access_keys', ['mindmap_id'], unique=False)
    op.create_index('idx_access_keys_user_id', 'access_keys', ['user_id'], unique=False)
    op.create_table('backup_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.Text(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backup_codes_code_hash', 'backup_codes', ['code_hash'], unique=False)
    op.create_index('idx_backup_codes_user_id', 'backup_codes', ['user_id'], unique=False)
    op.create_table('board_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=100), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.Column('author_email', sa.String(length=200), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_notice', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_author', 'board_posts', ['author_id'], unique=False)
    op.create_index('idx_posts_board', 'board_posts', ['board_id'], unique=False)
    op.create_index('idx_posts_created', 'board_posts', ['created_at'], unique=False)
    op.create_index('idx_posts_status', 'board_posts', ['status'], unique=False)
    op.create_table('credit_purchase_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('purchase_type', sa.Text(), nullable=False),
    sa.Column('package_type', sa.Text(), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('credit_amount', sa.Integer(), nullable=False),
    sa.Column('bonus_rate', sa.Float(), nullable=False),
    sa.Column('bonus_credits', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.Text(), nullable=False),
    sa.Column('transaction_id', sa.Text(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.Text(), nullable=True),
    sa.Column('stripe_checkout_session_id', sa.Text(), nullable=True),
    sa.Column('stripe_charge_id', sa.Text(), nullable=True),
    sa.Column('stripe_refund_id', sa.Text(), nullable=True),
    sa.Column('webhook_processed_at', sa.DateTime(), nullable=True),
    sa.Column('purchase_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_credits.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_purchase_date', 'credit_purchase_logs', ['purchase_timestamp'], unique=False)
    op.create_index('idx_credit_purchase_user', 'credit_purchase_logs', ['user_id'], unique=False)
    op.create_index('idx_purchase_logs_stripe_pi', 'credit_purchase_logs', ['stripe_payment_intent_id'], unique=False)
    op.create_index('idx_purchase_logs_stripe_session', 'credit_purchase_logs', ['stripe_checkout_session_id'], unique=False)
    op.create_table('credit_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('user_type', sa.Text(), nullable=False),
    sa.Column('ai_service', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('credit_type', sa.Text(), nullable=True),
    sa.Column('credits_deducted', sa.Integer(), nullable=False),
    sa.Column('request_preview', sa.Text(), nullable=True),
    sa.Column('response_preview', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_credits.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_usage_service', 'credit_usage_logs', ['ai_service', 'model_name'], unique=False)
    op.create_index('idx_credit_usage_user', 'credit_usage_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('node_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mindmap_id', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'node_id')
    )
    op.create_index('idx_node_ids_mindmap', 'node_ids', ['user_id', 'mindmap_id'], unique=False)
    op.create_index('idx_node_ids_node_id', 'node_ids', ['node_id'], unique=False)
    op.create_index('idx_node_ids_user_id', 'node_ids', ['user_id'], unique=False)
    op.create_table('package_id_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_id', sa.Text(), nullable=False),
    sa.Column('new_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['new_id'], ['subscription_packages.package_type'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('old_id')
    )
    op.create_table('board_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=100), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('admin_replied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['board_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['board_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_author', 'board_comments', ['author_id'], unique=False)
    op.create_index('idx_comments_post', 'board_comments', ['post_id'], unique=False)
    op.create_index('idx_comments_status', 'board_comments', ['status'], unique=False)
    op.create_table('board_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['board_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paid_credit_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('purchase_log_id', sa.Integer(), nullable=True),
    sa.Column('original_amount', sa.Integer(), nullable=False),
    sa.Column('remaining_amount', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_log_id'], ['credit_purchase_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_credits.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_paid_batches_expires', 'paid_credit_batches', ['expires_at', 'status'], unique=False)
    op.create_index('idx_paid_batches_fifo', 'paid_credit_batches', ['user_id', 'status', 'purchased_at'], unique=False)
    op.create_index('idx_paid_batches_user_status', 'paid_credit_batches', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_paid_batches_user_status', table_name='paid_credit_batches')
    op.drop_index('idx_paid_batches_fifo', table_name='paid_credit_batches')
    op.drop_index('idx_paid_batches_expires', table_name='paid_credit_batches')
    op.drop_table('paid_credit_batches')
    op.drop_table('board_files')
    op.drop_index('idx_comments_status', table_name='board_comments')
    op.drop_index('idx_comments_post', table_name='board_comments')
    op.drop_index('idx_comments_author', table_name='board_comments')
    op.drop_table('board_comments')
    op.drop_table('package_id_mapping')
    op.drop_index('idx_node_ids_user_id', table_name='node_ids')
    op.drop_index('idx_node_ids_node_id', table_name='node_ids')
    op.drop_index('idx_node_ids_mindmap', table_name='node_ids')
    op.drop_table('node_ids')
    op.drop_index('idx_credit_usage_user', table_name='credit_usage_logs')
    op.drop_index('idx_credit_usage_service', table_name='credit_usage_logs')
    op.drop_table('credit_usage_logs')
    op.drop_index('idx_purchase_logs_stripe_session', table_name='credit_purchase_logs')
    op.drop_index('idx_purchase_logs_stripe_pi', table_name='credit_purchase_logs')
    op.drop_index('idx_credit_purchase_user', table_name='credit_purchase_logs')
    op.drop_index('idx_credit_purchase_date', table_name='credit_purchase_logs')
    op.drop_table('credit_purchase_logs')
    op.drop_index('idx_posts_status', table_name='board_posts')
    op.drop_index('idx_posts_created', table_name='board_posts')
    op.drop_index('idx_posts_board', table_name='board_posts')
    op.drop_index('idx_posts_author', table_name='board_posts')
    op.drop_table('board_posts')
    op.drop_index('idx_backup_codes_user_id', table_name='backup_codes')
    op.drop_index('idx_backup_codes_code_hash', table_name='backup_codes')
    op.drop_table('backup_codes')
    op.drop_index('idx_access_keys_user_id', table_name='access_keys')
    op.drop_index('idx_access_keys_mindmap_id', table_name='access_keys')
    op.drop_index('idx_access_keys_key_id', table_name='access_keys')
    op.drop_index('idx_access_keys_key_hash', table_name='access_keys')
    op.drop_index('idx_access_keys_is_active', table_name='access_keys')
    op.drop_table('access_keys')
    op.drop_index('idx_users_stripe_customer', table_name='users_credits')
    op.drop_index('idx_users_credits_type', table_name='users_credits')
    op.drop_index('idx_users_credits_status', table_name='users_credits')
    op.drop_table('users_credits')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_totp_enabled', table_name='users')
    op.drop_index('idx_users_google_id', table_name='users')
    op.drop_index('idx_users_facebook_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_drive_settings_user', table_name='user_drive_settings')
    op.drop_table('user_drive_settings')
    op.drop_index('idx_token_usage_user_created', table_name='token_usage')
    op.drop_index('idx_token_usage_service', table_name='token_usage')
    op.drop_index('idx_token_usage_created', table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index('idx_subscription_packages_type', table_name='subscription_packages')
    op.drop_index('idx_subscription_packages_active', table_name='subscription_packages')
    op.drop_table('subscription_packages')
    op.drop_index('idx_webhook_events_type', table_name='stripe_webhook_events')
    op.drop_index('idx_webhook_events_id', table_name='stripe_webhook_events')
    op.drop_table('stripe_webhook_events')
    op.drop_index('idx_error_logs_source', table_name='error_logs')
    op.drop_index('idx_error_logs_level', table_name='error_logs')
    op.drop_index('idx_error_logs_expires', table_name='error_logs')
    op.drop_index('idx_error_logs_created', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_table('currency_exchange_rates')
    op.drop_index('idx_boards_sort', table_name='boards')
    op.drop_index('idx_boards_public', table_name='boards')
    op.drop_index('idx_boards_key', table_name='boards')
    op.drop_table('boards')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_logs_sensitivity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_event', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_ai_model_service', table_name='ai_model_pricing')
    op.drop_table('ai_model_pricing')
    op.drop_index('idx_admin_users_user_id', table_name='admin_users')
    op.drop_index('idx_admin_users_active', table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
